.class public GeneratedBytecode
.super java/lang/Object

.method public <init>()V
  aload_0
  invokenonvirtual java/lang/Object/<init>()V
  return
.end method

.method public static main([Ljava/lang/String;)V
  getstatic java/lang/System/out Ljava/io/PrintStream;
  ldc "This is generated bytecode!"
  invokevirtual java/io/PrintStream/print(Ljava/lang/String;)V
  return
.end method
